In [1]:
import pandas as pd

# 1. BiciMAD: Bicis por estación

In [2]:
bicimad_df = pd.read_csv('../data/raw/bicimad_stations.csv',sep='\t')
bicimad_df.head()

,Unnamed: 0,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry.type,geometry.coordinates
0,0,1,1a - Puerta del Sol A,3,1a,Puerta del Sol nº 1,1,1,30,0,0,0,Point,"[-3.7018341, 40.4172137]"
1,1,2,1b - Puerta del Sol B,3,1b,Puerta del Sol nº 1,1,1,30,0,0,0,Point,"[-3.701602938060457, 40.41731271011562]"
2,2,3,2 - Miguel Moya,3,2,Calle Miguel Moya nº 1,1,1,24,0,0,0,Point,"[-3.7058415, 40.4205886]"
3,3,4,3 - Plaza Conde Suchil,2,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,9,9,0,Point,"[-3.7069171, 40.4302937]"
4,4,5,4 - Malasaña,1,4,Calle Manuela Malasaña nº 5,1,0,24,23,1,0,Point,"[-3.7025875, 40.4285524]"

In [3]:
bicimad_df['no_available'].value_counts()

no_available
0    238
1     26
Name: count, dtype: int64

**Columnas relevantes:**

- **BiciMAD station (name):** 1a - Puerta del Sol A
- **Bikes available	(no_available):**  1

In [4]:
bicimad_df = bicimad_df.rename(columns={"name": "BiciMAD station",
                                        "no_available" : "Bikes available"})

# bicimad_df['name'].value_counts()

In [5]:
columns = ['BiciMAD station','Bikes available']
bicimad_dispo = bicimad_df[columns]

In [6]:
bicimad_dispo

                  BiciMAD station  Bikes available
0           1a - Puerta del Sol A                1
1           1b - Puerta del Sol B                1
2                 2 - Miguel Moya                1
3          3 - Plaza Conde Suchil                0
4                    4 - Malasaña                0
..                            ...              ...
259                    257 - INEF                0
260  258 - Ciudad Universitaria 1                0
261  259 - Ciudad Universitaria 2                0
262       260 - Facultad Biología                0
263        261 - Facultad Derecho                0

[264 rows x 2 columns]

In [7]:
bicimad_df = pd.read_csv('../data/results/bicimad_project_df.csv')
bicimad_df.head(2)

,Place of interest,Type of place,Place address,Distance from station in mts,BiciMAD station,BiciMAD address
0,"A (mas) ECU control urbanístico, S.L. Entidad ...",Instalaciones accesibles NO municipales,Calle Añastro 11 Planta Baja Puerta 10,1766.07,254 - Pío XII,Avenida Pío XII nº 3
1,"APFMPS, Residencia, centro de día y centro ocu...",Instalaciones accesibles NO municipales,Carretera Colmenar Viejo 13.6,9554.24,217 - Pedro Rico,Calle Pedro Rico nº 4

In [8]:
bicimad_project_df_test = bicimad_dispo.merge(bicimad_df, on=['BiciMAD station'], how='right')

In [9]:
column_order = ['Place of interest','Type of place','Place address','Distance from station in mts','BiciMAD station','BiciMAD address','Bikes available']
bicimad_df = bicimad_project_df_test[column_order]

In [10]:
bicimad_df.head(2)

,Place of interest,Type of place,Place address,Distance from station in mts,BiciMAD station,BiciMAD address,Bikes available
0,"A (mas) ECU control urbanístico, S.L. Entidad ...",Instalaciones accesibles NO municipales,Calle Añastro 11 Planta Baja Puerta 10,1766.07,254 - Pío XII,Avenida Pío XII nº 3,0
1,"APFMPS, Residencia, centro de día y centro ocu...",Instalaciones accesibles NO municipales,Carretera Colmenar Viejo 13.6,9554.24,217 - Pedro Rico,Calle Pedro Rico nº 4,0

In [11]:
bicimad_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Place of interest             409 non-null    object
 1   Type of place                 409 non-null    object
 2   Place address                 409 non-null    object
 3   Distance from station in mts  409 non-null    float64
 4   BiciMAD station               409 non-null    object
 5   BiciMAD address               409 non-null    object
 6   Bikes available               409 non-null    int64
dtypes: float64(1), int64(1), object(5)
memory usage: 22.5+ KB

In [12]:
# Exportando csv

from pathlib import Path
filepath = Path('../data/results/bicimad_vfinal_df.csv', index=False)  
filepath.parent.mkdir(parents=True, exist_ok=True) 
bicimad_df.to_csv(filepath, index=False, encoding='utf-8')

# 2. Biciparks: Puestos disponibles por estación

In [14]:
biciparks_df = pd.read_csv('../data/raw/bicipark_stations.csv', sep=';') # el delimitador es ';' si abrimos el csv
biciparks_df.head(2)

,Unnamed: 0,stationId,stationName,address,city,zip_code,total_places,free_places,enabled,reserved_places,geometry.type,geometry.coordinates
0,0,74,Bicipark Fuente de la Mora,Estación de Fuente de la Mora,Madrid,28050,10,9,1,0,Point,"[-3.6630679, 40.4846838]"
1,1,22,Bicipark Orense,"Avenida General Perón, 27",Madrid,28020,15,9,1,1,Point,"[-3.693897, 40.452973]"

**Columnas relevantes:**

- **stationName (BiciPARK station):** Bicipark Fuente de la Mora
- **free_places (Spots available):** 9

In [15]:
biciparks_df = biciparks_df.rename(columns={"stationName": "BiciPARK station",
                                        "free_places" : "Spots available"})

# bicimad_df['name'].value_counts()

In [16]:
columns = ['BiciPARK station','Spots available']
spots_bicipark = biciparks_df[columns]
spots_bicipark = spots_bicipark.drop(10)

In [17]:
spots_bicipark

             BiciPARK station  Spots available
0  Bicipark Fuente de la Mora                9
1             Bicipark Orense                9
2          Bicipark Montalban               15
3            Bicipark Almagro               12
4          Bicipark Recoletos                3
5           Bicipark Recuerdo               13
6          Bicipark Salamanca               -1
7     Bicipark Villa de Paris                8
8              Bicipark Pitis                7
9           Bicipark Aviación               10

In [18]:
spots_bicipark['Spots available'] = spots_bicipark['Spots available'].abs()

In [19]:
spots_bicipark

             BiciPARK station  Spots available
0  Bicipark Fuente de la Mora                9
1             Bicipark Orense                9
2          Bicipark Montalban               15
3            Bicipark Almagro               12
4          Bicipark Recoletos                3
5           Bicipark Recuerdo               13
6          Bicipark Salamanca                1
7     Bicipark Villa de Paris                8
8              Bicipark Pitis                7
9           Bicipark Aviación               10

In [20]:
biciparks_df = pd.read_csv('../data/results/biciparks_project_df.csv')
biciparks_df.head(2)

,Place of interest,Type of place,Place address,BiciPARK station,BiciPARK address,Distance from parking in mts
0,Administración Montalbán. AEAT,Instalaciones accesibles NO municipales,Calle Montalban 6,Bicipark Montalban,"Calle de Montalbán, 5",29.74
1,Biblioteca del Tribunal Supremo,Instalaciones accesibles NO municipales,Plaza Villa De Paris 1,Bicipark Villa de Paris,"Calle de Orellana, 23, 21",105.83

In [21]:
bicipark_project_df_test = spots_bicipark.merge(biciparks_df, on=['BiciPARK station'], how='right')

In [22]:
bicipark_project_df_test.head(1)

,BiciPARK station,Spots available,Place of interest,Type of place,Place address,BiciPARK address,Distance from parking in mts
0,Bicipark Montalban,15,Administración Montalbán. AEAT,Instalaciones accesibles NO municipales,Calle Montalban 6,"Calle de Montalbán, 5",29.74

In [23]:
column_order = ['Place of interest','Type of place','Place address','Distance from parking in mts','BiciPARK station','BiciPARK address','Spots available']
bicipark_df = bicipark_project_df_test[column_order]

In [24]:
bicipark_df.head()

,Place of interest,Type of place,Place address,Distance from parking in mts,BiciPARK station,BiciPARK address,Spots available
0,Administración Montalbán. AEAT,Instalaciones accesibles NO municipales,Calle Montalban 6,29.74,Bicipark Montalban,"Calle de Montalbán, 5",15
1,Biblioteca del Tribunal Supremo,Instalaciones accesibles NO municipales,Plaza Villa De Paris 1,105.83,Bicipark Villa de Paris,"Calle de Orellana, 23, 21",8
2,Oficina de Correos. Oficina Principal. Paseo d...,Instalaciones accesibles NO municipales,Paseo Prado 1,204.91,Bicipark Recoletos,"Paseo de Recoletos, 2",3
3,Oficina de Correos. Oficina Principal. Paseo d...,Instalaciones accesibles NO municipales,Paseo Prado 1,205.33,Bicipark Montalban,"Calle de Montalbán, 5",15
4,Biblioteca del Consejo General del Poder judicial,Instalaciones accesibles NO municipales,Calle Marques De La Ensenada 8,210.18,Bicipark Villa de Paris,"Calle de Orellana, 23, 21",8

In [25]:
# Exportando csv

from pathlib import Path
filepath = Path('../data/results/biciparks_vfinal_df.csv', index=False)  
filepath.parent.mkdir(parents=True, exist_ok=True) 
bicipark_df.to_csv(filepath, index=False, encoding='utf-8')

In [27]:
# Exportando csv

from pathlib import Path
filepath = Path('../modules/biciparks_project_df_v4.csv', index=False)  
filepath.parent.mkdir(parents=True, exist_ok=True) 
bicipark_df.to_csv(filepath, index=False, encoding='utf-8')